DATASETS_PATH = 'Datasets'
RESULTS_PATH  = 'Results'

EYE_RES = 736
IMG_HEIGHT = 736
IMG_WIDTH  = 896
TARGET_HEIGHT = 32
TARGET_WIDTH  = 32
RECEPTIVE_FIELD = 2 * TARGET_HEIGHT
DEG2PIXEL = 30
DOG_SIZE  = [[3, 0], [5, 1]]